<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <PackageOutputPath>..\nupkgs\</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Corsinvest.ProxmoxVE.Api.Extension" Version="9.2.3" />
    <PackageVersion Include="Corsinvest.ProxmoxVE.Api.Console" Version="9.2.3" />
  </ItemGroup>
</Project>