name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    uses: Corsinvest/.github/.github/workflows/cv4pve-tools-publish.yml@main
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      WINGET_TOKEN: ${{ secrets.WINGET_TOKEN }}
      AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
      HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}

    with:
      project-name: cv4pve-autosnap
      project-path: src/Corsinvest.ProxmoxVE.AutoSnap/Corsinvest.ProxmoxVE.AutoSnap.csproj
